#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         4
bspc config window_gap           6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a mpv state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Galculator state=floating
bspc rule -a lxappearance state=floating

bspc config focused_border_color	"#BD93F9"
bspc config normal_border_color		"#282A36"
bspc config active_border_color		"#8BE9FD"
bspc config presel_feedback_color	"#50FA7B"

picom --config ~/.config/picom/picom.conf &
feh --bg-fill ~/.config/Backgrounds/Dunmer_Door.jpg

##Polybar
polybar &

##Network Manager
nm-applet &

## Clipmemu start
# clipmenud &

## apps for systray if enabled
# volumeicon &
# nm-applet &
